"""Tiny SVG drawing kit for the architecture diagrams in Content.Server/AiAgent/README.md.

Hand-placed boxes and arrows, one palette, one font stack. The output is a plain .svg file
GitHub renders inline, readable on light and dark backgrounds (the canvas paints its own white
background) and regenerated by gen.py rather than edited by hand.

Every text and every arrow segment is recorded, and `check()` reports geometry that would read
badly: text overlapping text, arrows crossing or running along other arrows, arrows passing
through text, text spilling out of its box. Widths are measured with DejaVu Sans, which is wider
than the fonts GitHub viewers actually have, so what passes here passes there.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from html import escape

try:
    from PIL import ImageFont

    _FONTS = {
        (False, False): ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 100),
        (True, False): ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 100),
    }

    def _w(text: str, size: float, bold: bool = False) -> float:
        return _FONTS[(bold, False)].getlength(text) * size / 100

except Exception:  # pragma: no cover - fallback when Pillow or the font is missing

    def _w(text: str, size: float, bold: bool = False) -> float:
        return len(text) * size * (0.62 if bold else 0.57)


FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, 'Noto Sans', sans-serif"

INK = "#1f2328"
MUTED = "#59636e"
LINE = "#6e7781"
BORDER = "#8c959f"
LANE_BORDER = "#d0d7de"

TINTS = {
    "blue": "#eaf2fb", "green": "#eaf6ec", "warm": "#fbf3e6", "purple": "#f3eefa",
    "grey": "#f1f3f5", "red": "#fbeaea", "teal": "#e6f5f5",
}
ACCENTS = {
    "blue": "#0969da", "green": "#1a7f37", "warm": "#bc4c00", "purple": "#8250df",
    "grey": "#57606a", "red": "#cf222e", "teal": "#1b7c83",
}


@dataclass
class Node:
    x: float
    y: float
    w: float
    h: float
    lines: list[str]

    @property
    def cx(self):
        return self.x + self.w / 2

    @property
    def cy(self):
        return self.y + self.h / 2

    def top(self, dx=0):
        return (self.cx + dx, self.y)

    def bottom(self, dx=0):
        return (self.cx + dx, self.y + self.h)

    def left(self, dy=0):
        return (self.x, self.cy + dy)

    def right(self, dy=0):
        return (self.x + self.w, self.cy + dy)


@dataclass
class Svg:
    w: int
    h: int
    parts: list[str] = field(default_factory=list)
    # geometry for check(): (x0, y0, x1, y1, content, owner)
    texts: list[tuple] = field(default_factory=list)
    # (arrow_id, x1, y1, x2, y2)
    segments: list[tuple] = field(default_factory=list)
    # (x, y, w, h, name)
    boxes: list[tuple] = field(default_factory=list)
    _arrow_seq: int = 0

    # ----------------------------------------------------------------- text plumbing
    def _emit_text(self, x, y, s, size, bold, color, anchor="start", owner=None, halo=False):
        s = s.replace("`", "")
        wpx = _w(s, size, bold)
        x0 = {"start": x, "middle": x - wpx / 2, "end": x - wpx}[anchor]
        self.texts.append((x0, y - size * 0.78, x0 + wpx, y + size * 0.22, s, owner))
        weight = ' font-weight="700"' if bold else ""
        common = f'x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" font-family="{FONT}" font-size="{size}"{weight}'
        if halo:
            self.parts.append(
                f'<text {common} fill="none" stroke="#ffffff" stroke-width="5" '
                f'stroke-linejoin="round">{escape(s)}</text>'
            )
        self.parts.append(f'<text {common} fill="{color}">{escape(s)}</text>')
        return wpx

    # ----------------------------------------------------------------- primitives
    def lane(self, x, y, w, h, title, tint="grey", subtitle=None, subtitle_right=False):
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{TINTS[tint]}" '
            f'stroke="{LANE_BORDER}" stroke-width="1"/>'
        )
        tw = self._emit_text(x + 14, y + 22, title, 13, True, ACCENTS[tint], owner=("lane", title))
        if subtitle and subtitle_right:
            self._emit_text(x + w - 14, y + 22, subtitle, 12, False, MUTED, anchor="end",
                            owner=("lane", title))
        elif subtitle:
            self._emit_text(x + 14 + tw + 12, y + 22, subtitle, 12, False, MUTED,
                            owner=("lane", title))

    def node(self, x, y, w, h, *lines, accent=None, fill="#ffffff", dashed=False):
        """A box. First line bold, the rest muted; text is centred."""
        stroke = ACCENTS[accent] if accent else BORDER
        dash = ' stroke-dasharray="5 4"' if dashed else ""
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="8" fill="{fill}" '
            f'stroke="{stroke}" stroke-width="{1.6 if accent else 1.2}"{dash}/>'
        )
        if accent:
            self.parts.append(f'<rect x="{x}" y="{y}" width="5" height="{h}" rx="2.5" fill="{stroke}"/>')
        name = lines[0].replace("`", "")
        self.boxes.append((x, y, w, h, name))
        n = len(lines)
        line_h = 16
        total = 17 + (n - 1) * line_h
        y0 = y + (h - total) / 2 + 13
        for i, line in enumerate(lines):
            bold = i == 0
            self._emit_text(x + w / 2, y0 + i * line_h, line, 13 if bold else 12, bold,
                            INK if bold else MUTED, anchor="middle", owner=("node", name))
        return Node(x, y, w, h, list(lines))

    def text(self, x, y, s, size=12, color=MUTED, anchor="start", bold=False, owner=None):
        self._emit_text(x, y, s, size, bold, color, anchor=anchor, owner=owner or ("text", s))

    def note(self, x, y, w, lines, size=11.5):
        """Free-standing explanatory text, left-aligned, no box."""
        for i, line in enumerate(lines):
            self._emit_text(x, y + i * (size + 4), line, size, False, MUTED, owner=("note", lines[0]))

    def arrow(self, *pts, label=None, dashed=False, color=LINE, label_at=0.5, label_dy=-6,
              head=True, tail=False, label_anchor="middle", label_dx=0):
        self._arrow_seq += 1
        aid = self._arrow_seq
        for (ax, ay), (bx, by) in zip(pts, pts[1:]):
            self.segments.append((aid, ax, ay, bx, by))
        d = "M " + " L ".join(f"{px:.1f} {py:.1f}" for px, py in pts)
        dash = ' stroke-dasharray="6 4"' if dashed else ""
        mk = ' marker-end="url(#head)"' if head else ""
        mk += ' marker-start="url(#tailhead)"' if tail else ""
        self.parts.append(f'<path d="{d}" fill="none" stroke="{color}" stroke-width="1.6"{dash}{mk}/>')
        if label:
            segs = list(zip(pts, pts[1:]))
            lens = [((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2) ** 0.5 for a, b in segs]
            total = sum(lens) or 1
            target = label_at * total
            acc = 0
            lx, ly = pts[-1]
            for (a, b), ln in zip(segs, lens):
                if acc + ln >= target:
                    t = (target - acc) / ln if ln else 0
                    lx = a[0] + (b[0] - a[0]) * t + label_dx
                    ly = a[1] + (b[1] - a[1]) * t + label_dy
                    break
                acc += ln
            self._emit_text(lx, ly, label, 11.5, False, MUTED, anchor=label_anchor,
                            owner=("label", aid), halo=True)
        return aid

    # ----------------------------------------------------------------- checks
    def check(self, name="") -> list[str]:
        problems = []
        pad = 1.0  # tolerance in px

        def overlap(a, b):
            return not (a[2] - pad <= b[0] or b[2] - pad <= a[0] or a[3] - pad <= b[1] or b[3] - pad <= a[1])

        # text vs text
        for i in range(len(self.texts)):
            for j in range(i + 1, len(self.texts)):
                a, b = self.texts[i], self.texts[j]
                if overlap(a, b):
                    problems.append(f"text/text: {a[4]!r} × {b[4]!r}")

        # text outside its own box, or inside a foreign box
        for (x0, y0, x1, y1, s, owner) in self.texts:
            for (bx, by, bw, bh, bname) in self.boxes:
                inside_x = bx + 6 <= x0 and x1 <= bx + bw - 6
                inside_y = by <= y0 and y1 <= by + bh
                own = owner == ("node", bname)
                if own and not (inside_x and inside_y):
                    problems.append(f"text/box: {s!r} spills out of box {bname!r} ({x1 - x0:.0f}px in {bw - 12:.0f})")
                if not own and overlap((x0, y0, x1, y1), (bx, by, bx + bw, by + bh)):
                    problems.append(f"text/box: {s!r} overlaps box {bname!r}")

        # text vs canvas
        for (x0, y0, x1, y1, s, owner) in self.texts:
            if x0 < 2 or y0 < 2 or x1 > self.w - 2 or y1 > self.h - 2:
                problems.append(f"text/canvas: {s!r} leaves the canvas")

        # arrow vs arrow
        segs = self.segments
        for i in range(len(segs)):
            for j in range(i + 1, len(segs)):
                a, b = segs[i], segs[j]
                if a[0] == b[0]:
                    continue
                kind = _seg_relation(a[1:], b[1:])
                if kind:
                    problems.append(f"arrow/arrow ({kind}): #{a[0]} {a[1:]} × #{b[0]} {b[1:]}")

        # arrow vs text (a label may sit on its own arrow)
        for (aid, x1, y1, x2, y2) in segs:
            for (tx0, ty0, tx1, ty1, s, owner) in self.texts:
                if owner == ("label", aid):
                    continue
                if _seg_hits_rect((x1, y1, x2, y2), (tx0 + 1, ty0 + 1, tx1 - 1, ty1 - 1)):
                    problems.append(f"arrow/text: #{aid} passes through {s!r}")

        return [f"{name}: {p}" for p in problems]

    # ----------------------------------------------------------------- output
    def render(self) -> str:
        defs = (
            '<defs>'
            '<marker id="head" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" '
            f'orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="{LINE}"/></marker>'
            '<marker id="tailhead" viewBox="0 0 10 10" refX="1" refY="5" markerWidth="8" markerHeight="8" '
            f'orient="auto-start-reverse"><path d="M 10 0 L 0 5 L 10 10 z" fill="{LINE}"/></marker>'
            '</defs>'
        )
        body = "\n".join(self.parts)
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.w}" height="{self.h}" '
            f'viewBox="0 0 {self.w} {self.h}" font-family="{FONT}">\n{defs}\n'
            f'<rect width="{self.w}" height="{self.h}" rx="14" fill="#ffffff"/>\n{body}\n</svg>\n'
        )

    def save(self, path) -> list[str]:
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.render())
        return self.check(path.rsplit("/", 1)[-1])


# --------------------------------------------------------------------- geometry helpers
def _seg_relation(a, b, tol=3.0):
    """'' if the segments keep apart; 'cross' for a proper crossing; 'overlap' when they run
    along the same line and share more than a few pixels. Touching at an endpoint is fine."""
    ax1, ay1, ax2, ay2 = a
    bx1, by1, bx2, by2 = b

    def orient(px, py, qx, qy, rx, ry):
        return (qx - px) * (ry - py) - (qy - py) * (rx - px)

    o1 = orient(ax1, ay1, ax2, ay2, bx1, by1)
    o2 = orient(ax1, ay1, ax2, ay2, bx2, by2)
    o3 = orient(bx1, by1, bx2, by2, ax1, ay1)
    o4 = orient(bx1, by1, bx2, by2, ax2, ay2)

    alen = ((ax2 - ax1) ** 2 + (ay2 - ay1) ** 2) ** 0.5 or 1
    blen = ((bx2 - bx1) ** 2 + (by2 - by1) ** 2) ** 0.5 or 1
    # distance of b's endpoints from a's line, and vice versa
    d1, d2 = abs(o1) / alen, abs(o2) / alen
    d3, d4 = abs(o3) / blen, abs(o4) / blen

    if d1 < tol and d2 < tol:  # collinear-ish: check shared extent along a
        ux, uy = (ax2 - ax1) / alen, (ay2 - ay1) / alen
        ta = sorted([0, alen])
        tb = sorted([(bx1 - ax1) * ux + (by1 - ay1) * uy, (bx2 - ax1) * ux + (by2 - ay1) * uy])
        shared = min(ta[1], tb[1]) - max(ta[0], tb[0])
        return "overlap" if shared > 4 else ""

    if (o1 > 0) != (o2 > 0) and (o3 > 0) != (o4 > 0):
        # proper crossing unless it happens at an endpoint of both (a shared anchor point)
        near_end = min(d1, d2) < tol or min(d3, d4) < tol
        return "" if near_end else "cross"
    return ""


def _seg_hits_rect(seg, rect):
    x1, y1, x2, y2 = seg
    rx0, ry0, rx1, ry1 = rect
    if rx1 <= rx0 or ry1 <= ry0:
        return False
    # Liang–Barsky clipping
    dx, dy = x2 - x1, y2 - y1
    t0, t1 = 0.0, 1.0
    for p, q in ((-dx, x1 - rx0), (dx, rx1 - x1), (-dy, y1 - ry0), (dy, ry1 - y1)):
        if p == 0:
            if q < 0:
                return False
            continue
        t = q / p
        if p < 0:
            if t > t1:
                return False
            t0 = max(t0, t)
        else:
            if t < t0:
                return False
            t1 = min(t1, t)
    return t0 <= t1
